name: Deploy
on:
  workflow_dispatch: # Enables manual execution of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go version
      - uses: actions/setup-node@v4
      - run: npm -v

      - name: Install dependencies
        run: |
          GO111MODULE=on go install github.com/jaeles-project/gospider@latest
          npm install -g pagefind

      - name: Crawl wut.devkitpro.org
        run: |
          gospider -s "https://wut.devkitpro.org" -o .
          grep -Po "https://wut.devkitpro.org[^\s\]#]+" wut_devkitpro_org > links.txt
          sort links.txt| uniq > unique.txt

      - name: Download files
        run: wget --recursive --page-requisites --html-extension --convert-links --restrict-file-names=windows --domains=wut.devkitpro.org --no-parent -i unique.txt

      - name: Run pagefind
        run: |
          npx -y pagefind --site wut.devkitpro.org
          find wut.devkitpro.org -type f -name "*.html" -exec sed -i "s|</head>|<link href='/pagefind/pagefind-ui.css' rel='stylesheet'>\n<script src='/pagefind/pagefind-ui.js'></script>\n<div id='search'>\n</div>\n<script>\nwindow.addEventListener('DOMContentLoaded', (event) => {new PagefindUI({ element: '#search', showSubResults: true });});\n</script>\n</head>|g" {} +

      - name: Upload artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: wut.devkitpro.org/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

